# Use Golang image as the base image
FROM golang:alpine AS builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod .
COPY go.sum .

# Download dependencies
RUN go mod download

# Copy the Go program source code into the container
COPY . .

# Build the Go program
RUN go build -o network_capture .

# Use a minimal Alpine Linux image for the final container
FROM alpine:latest

# Set the current working directory inside the container
WORKDIR /app

# Copy the built executable from the previous stage
COPY --from=builder /app/network_capture .

# Expose the port your application listens on
# EXPOSE 8080

# Run the Go program
CMD ["./network_capture"]
